export const adminRole = 'admin'
export const creatorRole = 'creator'
export const userRole = 'user'
export const developmentStage = 'development'
export const productionStage = 'production'
export const uploadsAvatarPath = './uploads/avatar/'